/* This file is automatically generated */
#include <stdlib.h>
#include "pwcet-private.h"

#define NUM_TASKS 2

int taskdata_taskcount = NUM_TASKS;

int loophierarchy_task1(int l1, int l2)
{
	return 0;
}

int loophierarchy_task2(int l1, int l2)
{
	return 0;
}

int loopbounds_task1(int l1)
{
	return 0;
}

int loopbounds_task2(int l1)
{
	return 0;
}

int seq1_eta[7];
int seq1_cst1[3] = { 30, 25, 20 };
int seq1_cst2[4] = { 60, 50, 40, 18 };

formula_t seq_children[3] = {
	{
	 KIND_CONST,
	 {0},
	 {
	  1,
	  3,
	  seq1_cst1,
	  10,
	  },
	 NULL},
	{
	 KIND_CONST,
	 {0},
	 {
	  1,
	  4,
	  seq1_cst2,
	  15,
	  },
	 NULL},
};

task_t taskdata_tasktab[NUM_TASKS] = {
	{
	 "tache1",
	 {
	  loophierarchy_task1,
	  loopbounds_task1,
	  },
	 {
	  KIND_ALT,
	  {2},
	  {
	   0,
	   7,
	   seq1_eta,
	   0},
	  seq_children,
	  },
	 },
	{
	 "tache2",
	 {
	  loophierarchy_task1,
	  loopbounds_task1,
	  },
	 {
	  KIND_ALT,
	  {2},
	  {
	   0,
	   7,
	   seq1_eta,
	   0},
	  seq_children,
	  },
	 }

};
